version: '3.9'

services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - redis
      - postgres
    networks:
      - evolution-net

  postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-evolution}
      POSTGRES_USER: ${DATABASE_USERNAME:-evolution}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-evolution_secret}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    command: redis-server --port 6379 --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - evolution_redis:/data
    networks:
      - evolution-net

volumes:
  evolution_instances:
  postgres_data:
  evolution_redis:

networks:
  evolution-net:
    driver: bridge
